### ISSUE TITLE
New feature: Fixture Factory

### ISSUE THREAD

**Issue by lukadschaak** [teamneusta/pimcore-testing-framework#6]
I would love to have a fixture factory like we are already using at hubahead.

I would like to create fixtures, that can also depend on other fixtures to use them in tests. In compobination with Doctrine Test Bundle, the fixtures could be removed after test via rollback.

Maybe additionally, it would be great to have an command to execute a configurable list of fixtures to create test data for our local development.

**Comment by jdreesen** [comment]
See: https://github.com/teamneusta/pimcore-fixture-bundle/
